<?php
/**
 * @var $block \Epaard\Epaard_Whatsapp\Block\Adminhtml\System\Config\LaunchEpaardIntro
 */
?>
    <p class="note"><strong><?= $block->escapeHtml(__('Welcome to Epaard'))?></strong></p>
    <p class="note"><?= $block->escapeHtml(__('This module is developed by epaard.com we are specialist in all kind of e-commerce development.'))?>
        <?= $block->escapeHtml(__('we have expert magento and e-commerce developer.')) ?>
    </p>
    <p class="note">
        <?= $block->escapeHtml(__('Feel free for contact')) ?> <a href="mailto:sales@epaard.com" target="_blank" title="<?= $block->escapeHtmlAttr(__('sales@epaard.com')) ?>"><?= $block->escapeHtml(__('sales@epaard.com')) ?></a>
    </p>
    <p class="note">
        <?= $block->escapeHtml(__('Visit our website')) ?> <a href="https://epaard.com" target="_blank" title="<?= $block->escapeHtmlAttr(__('epaard.com')) ?>"><?= $block->escapeHtml(__('epaard.com')) ?></a>
    </p>
